name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      
      - name: Vet
        run: go vet -v ./...